# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  secret_key_base: c1189be7fd864d4ccd365f1df9be70f14782810df9e3fdc39e2b14fc56b480f82b0ad3c2472fd736ce970a8a8e5278af706d118001640ff8a2f31256cc6a735a

test:
  secret_key_base: 65d9b883d9b81ea06994dba8814591d9812f76c3b2a64e81ac1b4d7d8c384394380154a2e1b7407716b5da22b424ebeeb2a86ea500b079f1e45bee2e416e9b1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
